server:
  port: 10004
  servlet:
    encoding:
      charset: UTF-8
    context-path: /

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#Thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
# Database
  datasource:
    driver-class-name:
      com.mysql.cj.jdbc.Driver
    url:
      jdbc:mysql://gyguswlsgh.ciiiy3dtxwx4.ap-northeast-2.rds.amazonaws.com:1521/HyoHyunJinHo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username:
      gyguswlsgh
    password:
      gyguswlsgh
# H2 enable
  h2:
    console:
      enabled: true
      path: /h2-console
#Security id & pw
  security:
    user:
      name: admin
      password: 1111
#Google Mail Send
  mail:
    host: smtp.gmail.com
    port: 587
    username: ses1238@gmail.com
    password: tdrrqd99
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
#Auto Reload
  devtools:
    livereload:
      enabled: true
#mybatis
mybatis:
  type-aliases-package: com/library/application/ResponseVo/**
  mapper-locations: mapper/**.xml
#Token
token:
  expiration_time: 864000000 #10 days
  secret: user_login
#Linux & window  path
custom:
  path:
    upload-imges: 'D:/library/'
    upload-pdf: 'D:/pdf/'
  Linux:
    upload-imges: 'home/ec2-user/Library-Data/img'
    upload-pdf: 'home/ec2-user/Library-Data/pdf'
#URL location
  location:
    bookSave: /library/booksave
    bookReturn: /library/bookreturn
    userInfo: /user-service/user/info
    userDelete: /user-service/user/
    autoReturn: /user-service/user/auto_return
    bookSelect: /pdfview?file=

