server:
  port: 10004
  servlet:
    encoding:
      charset: UTF-8


spring:
  mvc:

    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driver-class-name:
      com.mysql.cj.jdbc.Driver
    #oracle.jdbc.driver.OracleDriver
    url:
      jdbc:mysql://gyguswlsgh.ciiiy3dtxwx4.ap-northeast-2.rds.amazonaws.com:1521/HyoHyunJinHo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    #jdbc:oracle:thin:@localhost:1521/xe
    username:
      gyguswlsgh
    #ses9892
    password:
      gyguswlsgh
    #1234
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    user:
      name: admin
      password: 1111

mybatis:
  type-aliases-package: com/library/application/ResponseVo/**
  mapper-locations: mapper/**.xml

token:
  expiration_time: 864000000 #10 days
  secret: user_login
custom:
  path:
    upload-imges: 'D:/library/'
    upload-pdf: 'D:/pdf/'
  location:
    bookSave: /library/booksave
    bookReturn: /library/bookreturn
    userInfo: /user-service/info/
    userDelete: /user-service/user/
    autoReturn: /user-service/user/auto_return/
    bookSelect: /pdfview?file=
#http://localhost:10004/user-service/info/admin

